# Generated by Django 2.0.7 on 2018-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0002_auto_20180724_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='comment',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
