# Generated by Django 2.0.7 on 2018-07-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0003_auto_20180724_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
    ]
